### ISSUE TITLE
Need help to set task on the same line  for each resource

### ISSUE THREAD

**Issue by saydujjaman** [jakesee/ganttchart#11]
Hi, I need to set task in the same line to show the resource schedule, how can we do that? I also want to implement zoom in/out feature board. how can we do that?

**Comment by UltiWolf** [comment]
saydujjaman:  I too am looking for a way to set a task (new or additional) in the same line but further in the timeline.  Have you had any luck with this?

**Comment by UltiWolf** [comment]
saydujjaman:  I am looking at the code in Chart.cs.  The _DrawTasks method does not allow the drawing of multiple tasks on a single line.  The code simply iterates through the list of tasks and draws them consecutively 1 below the previous incrementing the row variable at the end of each loop.

**Comment by jakesee** [comment]
You can use split tasks into parts and draw the separate parts in the same row.
