### ISSUE TITLE
操作数据库

### ISSUE THREAD

**Issue by 0suneveryday0** [jakesee/ganttchart#9]
将任务数据从数据库中读取并显示的功能我已经实现了，但是如何将修改后的数据提交的数据库中还未实现。程序中所有的时间都是timespan类型，而要保存的数据都是DateTime类型的。有没有什么好的方法可以实现修改的数据能提交的数据库中呢？

**Comment by 0suneveryday0** [comment]
已解决，IProject中增加如下代码
/// <summary>
        /// 项目开始时间
        /// </summary>
        public DateTime StartDate { get; set; }
        /// <summary>
        /// 项目结束时间
        /// </summary>
        public DateTime EndDate { get; set; }
        /// <summary>
        /// 标识符
        /// </summary>
        public object Id { get; set; }

使用
var stage = new MyTask(project) { Name = "P_(" + schedule.Id + ")" + stageName,StartDate= beginDate, EndDate = endDate,Id=schedule.Id};

**Comment by jakesee** [comment]
谢谢你！希望一切顺利！
